# version is required, 2 is a good choice
# it is not the version of the project
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.13'
  jobs:
    pre_build:
      - rm -rf _readthedocs/
    post_build:
      - python src/refiner.py
python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py
  fail_on_warning: true

# formats:
#   - pdf
#   - epub
