# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 向阳花花农的花海
author: 向阳花花农 The Sunflorist</br><code>the.sunflorist@foxmail.com</code>
copyright: '2024'
logo: 'images/Van_Gogh_Fields_960x270.png'
only_build_toc_files: true

# Force re-execution of notebooks on each build
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Parse and render settings
parse:
  # See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
  myst_enable_extensions:
    - fieldlist

html:
  favicon: 'images/Van_Gogh_Moon_200x200.png'
  announcement: 该网页使用<a href="https://jupyterbook.org/en/stable/intro.html">Jupyter Book</a>进行搭建🏗️ 使用<a href="https://pages.github.com">GitHub Pages</a>完成部署和发布🚀
  extra_footer: 向阳花花农原创作品，保留所有版权。</br>The Sunflorist's originals. All rights reserved.

# See https://jupyterbook.org/en/stable/advanced/sphinx.html
sphinx:
  config:
    language: zh
