# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 向阳花花农的花海
author: 向阳花花农 The Sunflorist
copyright: '2024'
logo: ''
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ''
  extra_footer: 向阳花花农原创作品，保留所有版权，商用授权请联系<code>the.sunflorist@foxmail.com</code>。</br>The Sunflorist's originals. All rights reserved. For commercial authorization, please contact <code>the.sunflorist@foxmail.com</code>.
