# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 向阳花花农的诗画集
author: 向阳花花农
copyright: '2024'
logo: ''
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: ''
  extra_footer: 向阳花花农原创作品，版权所有。个人免费收藏欣赏，分享转载请注明原作者，禁止用于任何盈利活动。
